name: Publish to NPM

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"

jobs:
  publish:
    runs-on: [deploy, uopve]
    container:
      image: node:20-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate

      - run: pnpm build

      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_SEC }}
          npm publish --access public
