name: Publish to NPM

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: [deploy,uopve]
    container:
      image: node:20-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: show env
        uses: ls

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm install

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: |
          npm set registry.npmjs.org/:_authToken=${{ secrets.NPM_SEC }}
          npm publish --access public
